services:
  backend:
    build:
      context: ./FizzBuzzGameApi
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - fizzbuzz_data:/app/Data
  frontend:
    build:
      context: ./fizzbuzz-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:5000/api
    depends_on:
      - backend

volumes:
  fizzbuzz_data: 